### ISSUE TITLE
SinusoidalMixin causes errors for current sources

### ISSUE THREAD

**Issue by xesscorp** [FabriceSalvaire/PySpice#102]
In HighLevelElement.py, the `SinusoidalMixin`, `PulseMixin`, etc all throw errors when you use current sources because the mix-ins expect amplitudes, offsets, etc to be voltages (`as_V()`) and not currents.

(Even though I keep reporting issues, I do love PySpice. It's saving me a lot of work.)

**Comment by FabriceSalvaire** [comment]
Indeed, thanks ! I hope iit is fixed now !

**Comment by xesscorp** [comment]
Fixed. Thanks!
