### ISSUE TITLE
Initial steps when charging capacitor are incorrect

### ISSUE THREAD

**Issue by solarjoe** [FabriceSalvaire/PySpice#151]
Linux64, Py 3.6, PySpice master, ngspice-subprocess, ngSpice 27

When running the code below the first steps of the calculation seem incorrect:

![grafik](https://user-images.githubusercontent.com/10460113/53622457-26c7c580-3bfa-11e9-86d1-e9bff589631d.png)

This does not depend on the temporal resolution. If the step size is changed the shape does not disappear, it only scales different. With a very fine resolution it seems to disappear, but it is still there.

It is probably related to the numerical method used and is has not fully converged.
Is there a setting in PySpice / ngspice to check the quality of the solution?

```
import PySpice.Spice.Simulation
import matplotlib.pyplot as plt

import PySpice.Logging.Logging as Logging
logger = Logging.setup_logging()

####################################################################################################

from PySpice.Spice.Netlist import Circuit
from PySpice.Unit import *

from PySpice.Probe.Plot import plot

circuit = Circuit('RC circuit, charging capacitor')

capa = 1000@u_uF
resi = 47@u_kΩ

tau = capa * resi

print(tau)

circuit.V('Vin', 'in', circuit.gnd, 10@u_V)
circuit.R(1, 'in', 'out', resi)
circuit.C(2, 'out', circuit.gnd, capa)#, ic=0@u_V)

simulator = circuit.simulator(temperature=25, nominal_temperature=25)

simulator.initial_condition(out=0@u_V )

step_time = 1000@u_ms
analysis = simulator.transient(step_time=step_time, end_time=5*tau)

figure = plt.figure(1, (20, 10))

axe = plt.subplot(121)
axe.grid()
axe.plot(analysis['in'], 'ro')
axe.plot(analysis['out'], 'g.')
axe.set_ylim(0, 11)
axe.set_xlabel('t [s]')
axe.set_ylabel('[V_c]')
axe.legend(('Vin [V]', 'Vout [V]'), loc=(.8,.8))

plt.tight_layout()
plt.show()

```

**Comment by emrahacar** [comment]
try 

`simulator = circuit.simulator(temperature=25, nominal_temperature=25, use_initial_condition=True)
`

**Comment by solarjoe** [comment]
Thanks for your reply, I tried it, but when I look at the generated string in the debug console the `uic` does not show up:
```
.title Resistor Bridge
Vin in 0 10V
R1 in out 47kOhm
C2 out 0 1000uF
.options TNOM = 25°C
.options TEMP = 25°C
.ic V(out)=0V
.tran 1000ms 235.0s 0s
.end
```

The initial conditions are listed, but the `.tran` line should be 

`.tran 1000ms 235.0s 0s UIC`

Can does the `UIC` show up on your installation?

**Comment by solarjoe** [comment]
Ok, at least I found out why the `UIC` is not working, you need to pass it to 

`analysis = simulator.transient(step_time=step_time, end_time=5*tau, use_initial_condition=False)`

and not to

`simulator = circuit.simulator(temperature=25, nominal_temperature=25, use_initial_condition=True`

Something changes, but still not correct.

`use_initial_condition=False`:

![grafik](https://user-images.githubusercontent.com/10460113/53754216-90bec400-3eb3-11e9-959d-7a98891cb0bd.png)

`use_initial_condition=True`:

![grafik](https://user-images.githubusercontent.com/10460113/53754317-e2674e80-3eb3-11e9-8549-2e53744f1907.png)

???

**Comment by solarjoe** [comment]
Ok, I found the problem. I was using matplotlib's `plt.plot` instead of `PySpice.Probe.Plot.plot` and the abscissa did not match.
