### ISSUE TITLE
PyYAML warning over logging

### ISSUE THREAD

**Issue by TheoMathurin** [FabriceSalvaire/PySpice#155]
### Environment
Ubuntu 18.04, Python 3.7.2, PySpice 1.3.2, ngspice 27 as subprocess

When creating logger (`logger = Logging.setup_logging()`), the following warning is issued:
```
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
logging_config = yaml.load(open(logging_config_file_name, 'r'))
```
The link redirects [here](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation) where we learn that the deprecation followed a CVE filed against PyYAML over the safety of the `load` function.

This is a benign issue, as the warning does not prevent the use of PySpice. It's just somewhat annoying, while there is a ready-made and simple solution available.

The advice given to developers is to specify a loader when calling the `load` function:
> If you are the author/maintainer of the Python code that is triggering the warning, the best way to stop getting the warning is to specify the Loader= argument like so:
`yaml.load(input, Loader=yaml.FullLoader)`

Still, in the meantime users can chose to disable the warning using the PYTHONWARNINGS environment variable.

**Comment by FabriceSalvaire** [comment]
fixed in 198a33958967b150a851b3d8bc9a88b3ebc16af9
