### ISSUE TITLE
Expired cerificate of documentation page

### ISSUE THREAD

**Issue by chrisgee** [FabriceSalvaire/PySpice#161]
### Environment (OS, Python version, PySpice version, simulator)
Firefox

### Expected Behaviour
open the link to the documentation -> Documentation shown

### Actual Behaviour
Firefox rejects showing the web site because the SSL certificate is expired on July 7th 2019

**Comment by FabriceSalvaire** [comment]
rebooted sever but seems recurrent

**Comment by akrinke** [comment]
Again, the SSL certificate expired on June 6 2021.
