### ISSUE TITLE
Transmission line does not respect arguments

### ISSUE THREAD

**Issue by RossWilliamson** [FabriceSalvaire/PySpice#169]
### Environment (OS, Python version, PySpice version, simulator)

Ubunutu, Anaconda python 3.7,3 PySpice 1.3.2

### Expected Behaviour

Expect no error
circuit.LosslessTransmissionLine('sdfselay', 'output', circuit.gnd, 'input', circuit.gnd, Z0=50, TD=40e-9)
### Actual Behaviour

States that keyword is required but is present in the call
~/anaconda3/lib/python3.7/site-packages/PySpice/Spice/BasicElement.py in __init__(self, name, *args, **kwargs)

   1471         if not (('time_delay' in kwargs) ^
   1472                 (('frequency' in kwargs) & ('normalized_length' in kwargs))):
-> 1473             raise NameError('Either TD or F, NL must be specified')
   1474 
   1475         super().__init__(name, *args, **kwargs)

NameError: Either TD or F, NL must be specified

Note that it is very difficult to know what arguments to use for example the following works buy how are we supposed to know to use the arguments impedance and time_delay?  I cannot find anywhere in the documentation what the keywords should be. For example what are the keywords for  SingleLossyTransmissionLine?

circuit.LosslessTransmissionLine('dsdfselay', 'output', circuit.gnd, 'input', circuit.gnd, impedance=50, time_delay=40e-9)

**Comment by FabriceSalvaire** [comment]
fixed parameter check from 62e0c0ec3aa71a313e6f32465bc620678ae8fd5c
