### ISSUE TITLE
symbolic links to /home/fabrice

### ISSUE THREAD

**Issue by thomaslima** [FabriceSalvaire/PySpice#18]
Bonjour Fabrice,

Il y a des liens symboliques pour certains fichiers dans la doc de sphinx. Exemple: doc/sphinx/source/examples/fundamental-laws/millman-theorem.py pointe vers /home/fabrice/home/developpement/PySpice/examples/fundamental-laws/millman-theorem.py

Cordialement

**Comment by FabriceSalvaire** [comment]
The documentation mechanics (and git repository ?) needs some cleanup.

**Comment by FabriceSalvaire** [comment]
should be done
