### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by sakibmohammad** [FabriceSalvaire/PySpice#183]
Hi, I am new to Python. I am using PySpice for a project (I'm on Win10). I have installed every package correctly (that I know of). I am trying to run this example: https://github.com/FabriceSalvaire/PySpice/blob/master/examples/diode/voltage-multiplier.py and getting this error
![Capture](https://user-images.githubusercontent.com/60448661/73807606-b83ca180-4792-11ea-94ae-7324580a651b.PNG)

What can I do? Any help will be really appreciated. 
Thanks.

**Comment by stuarteberg** [comment]
I am not a spice expert, but I think the examples won't work unless you have a library of SPICE component models installed on your machine.  In the example you mentioned, the following lines are responsible for locating that library:

```
libraries_path = find_libraries()
spice_library = SpiceLibrary(libraries_path)
```

But some advice on where to find and install such models would be appreciated.

**Comment by sakibmohammad** [comment]
Thank you for your response. I was able to run the examples. I was to change the source code of the library to make sure it can detect the ngspice library. Then I had to download the github repository of PySpice and,  had to change the following line, and add the library path manually. 

libraries_path = find_libraries()
