### ISSUE TITLE
Monte Carlo in PySpice

### ISSUE THREAD

**Issue by sakibmohammad** [FabriceSalvaire/PySpice#190]
### Environment (Win10, 3.8, 1.3.2, ngspice)

Hello,
I am simulating a solar cell circuit in pyspice where I have to use statistical values of resistors using Monte Carlo simulation. But I don't have a clue about that. It would be really great if someone could help me with this. Thank you.

P.S: I am a beginner in Python.

**Comment by FabriceSalvaire** [comment]
You should ask on forum
