### ISSUE TITLE
Several HighLevelElements (Sinusoidal, AmplitudeModulated...) should also implement currentSource

### ISSUE THREAD

**Issue by rafadose** [FabriceSalvaire/PySpice#20]
Several high level elements (like _sinusoidal_, _amplitudeModulated_, _exponential_...) are implemented as voltage only when they can also be current sources. 
I suggest to implement a generic _Source_ in _BasicElement_ with the attribute _type_ to select between voltage and current and use this _Source_ in all _HighLevelElements_.

Apologies, this is a known issue; I have just noticed the Fixme comment in HighLevelElement.py:
`# Fixme: these waveforms can be current sources as well`

Regards

**Comment by FabriceSalvaire** [comment]
fixed in 47d7f9975319f224e74a603e128280e1009f9c78
