### ISSUE TITLE
Possible to generate sparse matrix and run simulation on GPUs via tensorflow?

### ISSUE THREAD

**Issue by jifanchn** [FabriceSalvaire/PySpice#239]
Is it possible to run simulations on GPUs?

I believe this is much faster than CPU simulations, and this is so exciting!!!

And is there any kindhearted person who has some benchmarks on different solvers?

Thanks.

**Comment by jifanchn** [comment]
And I can also make some contributions if this is welcomed here.

**Comment by FabriceSalvaire** [comment]
Simulation is done in the simulator ngspice or xyce, PySpice is just a wrapper
