### ISSUE TITLE
pure python implementation

### ISSUE THREAD

**Issue by unnir** [FabriceSalvaire/PySpice#29]
Hi all,

are you planning *thinking about the pure python implementation?

**Comment by FabriceSalvaire** [comment]
If you mean a Python ngspice clone, the answer is no. Moreover there are projects addressing this topic.

**Comment by unnir** [comment]
pity, nevertheless thank you for your answer, the reason of my question, I'm a mac user and it ist so easy to set up the ngspice connection on MacOS.
