### ISSUE TITLE
WinError 2 - Can not find file

### ISSUE THREAD

**Issue by ottarsk** [FabriceSalvaire/PySpice#32]
Hi,

Running examples, but they all stop on creating analysis.

Running win 10, python 3.5 64 bit. Installed PySpice with "pip install PySpice", and then installed "cffi" after. Is more information needed?

Thanks for guidance,

analysis1 = simulator1.ac(start_frequency=100, stop_frequency=kilo(10), number_of_points=100,  variation='dec')
Leaves the following error:

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-20-d2d3b53086ce> in <module>()
      1 
----> 2 analysis1 = simulator1.ac(start_frequency=100, stop_frequency=kilo(10), number_of_points=100,  variation='dec')

c:\users\bruker\appdata\local\programs\python\python35\lib\site-packages\PySpice\Spice\Simulation.py in ac(self, *args, **kwargs)
    383     def ac(self, *args, **kwargs):
    384 
--> 385         return self._run('ac', *args, **kwargs)
    386 
    387     ##############################################

c:\users\bruker\appdata\local\programs\python\python35\lib\site-packages\PySpice\Spice\Simulation.py in _run(self, analysis_method, *args, **kwargs)
    417         super()._run(analysis_method, *args, **kwargs)
    418 
--> 419         raw_file = self._spice_server(str(self))
    420         self.reset_analysis()
    421 

c:\users\bruker\appdata\local\programs\python\python35\lib\site-packages\PySpice\Spice\Server.py in __call__(self, spice_input)
    144                                    stdin=subprocess.PIPE,
    145                                    stdout=subprocess.PIPE,
--> 146                                    stderr=subprocess.PIPE)
    147         input_ = str(spice_input).encode('utf-8')
    148         stdout, stderr = process.communicate(input_)

c:\users\bruker\appdata\local\programs\python\python35\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds)
    674                                 c2pread, c2pwrite,
    675                                 errread, errwrite,
--> 676                                 restore_signals, start_new_session)
    677         except:
    678             # Cleanup if the child failed starting.

c:\users\bruker\appdata\local\programs\python\python35\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
    953                                          env,
    954                                          cwd,
--> 955                                          startupinfo)
    956             finally:
    957                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] Systemet finner ikke angitt fil

**Comment by FabriceSalvaire** [comment]
I feel ngspice executable is not found in your path. Did you install ngspice ?
