### ISSUE TITLE
Errors on Windows install

### ISSUE THREAD

**Issue by wattse** [FabriceSalvaire/PySpice#36]
Hi Fabrice,

I saw that you recently added Windows support, and I recently installed PySpice on Windows. I have encountered a few issues.
First was in Logging\Logging.py, lines 44-47 need unindenting if I am predicting your intention correctly.
Second is in Spice\NgSpice\Shared.py: its missing an import platform at the top.

I'll report any more that I find.

Cheers!

**Comment by FabriceSalvaire** [comment]
Ah yes, test on Linux doesn't means its ok on Windows ...

**Comment by FabriceSalvaire** [comment]
Thanks for reporting !

fixed in a6a67544ca15e20d75a215ea6ce943f753ab4738
