### ISSUE TITLE
Incorrect Windows path for C:\Program Files\Spice64

### ISSUE THREAD

**Issue by eps82** [FabriceSalvaire/PySpice#47]
### Environment (OS, Python version, PySpice version, simulator)
Windows 7
Python 3.6.1 (WinPython distribution 3.6.1.0Qt5)
PySpice 1.1.2
ngspice (whichever version http://ngspice.sourceforge.net/experimental/ngspice-26plus-scope-inpcom-6-64.7z is)

### Expected Behaviour
Default path for ngspice should be C:\Program Files\Spice64

### Actual Behaviour
PySpice looks for C:Program Files\Spice64 instead

### Steps to reproduce the behaviour
Just follow the installation steps for Windows

### Suggested fix
Path can be redefined manually. Personally, I just edited site-packages\PySpice\Spice\NgSpice\Shared.py

The problem lies here (lines 1079+):
if ConfigInstall.OS.on_windows:
    drive = os.getenv('SystemDrive') or 'C:'
...
    ngspice_path = os.path.join(drive, 'Program Files', ngspice_dirname)

As exotic as this may sound, os.path.join('C:', 'Program Files') actually returns 'C:Program Files', which doesn't cut it. I fixed it as os.path.join(drive, os.sep, 'Program Files', ... ) instead, which introduces the proper separator. (To be clear, I edited it locally; I'm not familiar with github so I don't know how to contribute with source)

**Comment by FabriceSalvaire** [comment]
Thanks for reporting !

fixed in b9b8197f1d84ed8cfcc8a2d9363abdc254759e57

**Tested example on vm, it works now**
