### ISSUE TITLE
Initial Conditions on Capacitors and Inductors attributes are not working

### ISSUE THREAD

**Issue by IgnacioRubioScola** [FabriceSalvaire/PySpice#49]
The initial condition from 'ic' parameter is not working, but initializing the voltage node works well (commented). The problem is with inductors, how can I initialize the simulation with current initial conditions?

Here the code for a RC circuit:

```
import matplotlib.pyplot as plt

from PySpice.Probe.Plot import plot
from PySpice.Spice.Library import SpiceLibrary
from PySpice.Spice.Netlist import Circuit
from PySpice.Unit import *


circuit = Circuit('RCCircuit')
circuit.V('input', 'node_01', circuit.gnd, 15@u_V)
circuit.R(1, 'node_01', 'node_02', 1000@u_kΩ)
circuit.C(1,'node_02',circuit.gnd, 50@u_uF, ic=0@u_V)

Tf =300@u_s
T = 0.1@u_s

simulator = circuit.simulator(temperature=25, nominal_temperature=25)
#simulator.initial_condition(node_02=0)
analysis = simulator.transient(step_time=T/10, end_time=Tf)

figure = plt.figure(1)
plot(analysis['node_01'])
plot(analysis['node_02'])
plt.show()
```

**Comment by FabriceSalvaire** [comment]
Look at ngspice manual **3.2.13 Capacitor or inductor with initial conditions**

It is an XSpice extension and unfortunately A device are not yet implemented.

**Comment by FabriceSalvaire** [comment]
A basic implementation should be easy, similar to X

However a complete implementation requires a good understanding of XSpice.

**Comment by FabriceSalvaire** [comment]
Devel branch implements partially A device

**Comment by FabriceSalvaire** [comment]
Devel branch implements raw spice pass through

**Comment by solarjoe** [comment]
Linux64, Py 3.6, PySpice master, ngspice-subprocess, ngSpice 27

I am seeing the same problem. using `initial_condition` it works fine.

As mentioned above, the devel branch seems to fix this issue, but I can't use it.
I need the changes made in https://github.com/FabriceSalvaire/PySpice/issues/110 and they are only in the master branch.
