### ISSUE TITLE
Typo in setup.py dependencies

### ISSUE THREAD

**Issue by mikeanthonywild** [FabriceSalvaire/PySpice#84]
AFAIK `requires` isn't a valid keyword argument for setuptools. This used to be `install_requires` but was changed in 230fc22. I assume this is a typo?

**Comment by FabriceSalvaire** [comment]
Oops I don't remember why ? Read outdated doc ???

https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies

https://packaging.python.org/tutorials/distributing-packages/#install-requires

`install_requires=['peppercorn'],`

https://packaging.python.org/tutorials/distributing-packages/#python-requires

`python_requires='>=3',`

> In addition, only versions 9.0.0 and higher of pip recognize the python_requires metadata.

**Comment by FabriceSalvaire** [comment]
fixed in dc9287fb56aa5167394e62f7197c64a4c7ccf183

**Comment by FabriceSalvaire** [comment]
uploaded new version

look at  #85
