### ISSUE TITLE
u_F is not working properly

### ISSUE THREAD

**Issue by fb39ca4** [FabriceSalvaire/PySpice#86]
### Environment
Linux, Python 3.6.3, PySpice 1.1.3, NgSpice 27-1

### Expected Behaviour
The u_F unit should behave as expected. Assigning 1e-6@u_F to a capacitor should give the same results as 1@u_uF, 1000@u_nF, or any of the other equivalents.

### Actual Behaviour
Assigning a capacitor a value 1e-6@u_F gives it a capacitance 10^15 times smaller than it should be. Could this be related to some confusion between the F in farad and femto?

### Steps to reproduce the behaviour
If everything was working properly, all of the output plots would be the same.

```
import matplotlib.pyplot as plt
import numpy as np

from PySpice.Probe.Plot import plot
from PySpice.Spice.Netlist import Circuit
from PySpice.Unit import *

capacitances = [1e6@u_pF, 1e3@u_nF, 1@u_uF, 1e-3@u_mF, 1e-6@u_F]
for capacitance in capacitances:
	circuit = Circuit(str(capacitance))
	circuit.Sinusoidal("s", "input", circuit.gnd)
	circuit.C("1", "input", "output", capacitance)
	circuit.R("1", "output", circuit.gnd, 1@u_kOhm)
	results = circuit.simulator().ac(start_frequency=1@u_Hz, stop_frequency = 1e9@u_THz, number_of_points = 500, variation='dec')
	plt.semilogx(results.frequency, np.abs(results.output))

plt.legend(capacitances, loc="middle center")
plt.show()
```

**Comment by FabriceSalvaire** [comment]
Yes,  1@u_F is rendered as 1F in spice netlist and understood as 1 femto by spice since it is case independent.

**Resolution:** implement a trick to remove F in this case, is space valid ???, check for similar case
